[tool.poetry]
name = "emplode"
packages = [
    {include = "emplode"},
]
version = "0.1"
description = "Let language models run code locally."
authors = ["Shouryamaan Jain <smj@emplode.com>, Tanishq Chugh <tanishq@emplode.com>, Rexan Wong <rexan@emplode.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
openai = "^1.106.1"
rich = "^14.1.0"
tiktoken = "^0.11.0"
tokentrim = "^0.1.13"

[tool.poetry.group.dev.dependencies]
pytest = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
emplode = "emplode:cli"
